### ISSUE TITLE
Rewrite Profile

### ISSUE THREAD

**Issue by martialblog** [vision-it/vision-firewall#1]
Working on a complete rewrite to make this more flexible:
https://github.com/martialblog/vision-firewall/tree/rewrite

This will be included in the default server profile once it's finished. 

**ATTENTION**: Don't merge until rules are fully tested. I'm serious...

**Comment by martialblog** [comment]
**TODO:** Add more sane default rules and test everything in Vagrant.

**Comment by martialblog** [comment]
**TODO:** Also needs to be tested/adjusted for Xen

**Comment by darkstar42** [comment]
**TODO**: still removes Docker rules from _FORWARD_ chain

_pre_
> Chain FORWARD (policy DROP)
> target     prot opt source               destination         
> DOCKER-ISOLATION  all  --  anywhere             anywhere            
> DOCKER     all  --  anywhere             anywhere            
> ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
> ACCEPT     all  --  anywhere             anywhere            
> ACCEPT     all  --  anywhere             anywhere 

_diff pre post_
> < ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
> < ACCEPT     all  --  anywhere             anywhere            
> < ACCEPT     all  --  anywhere             anywhere

**Comment by darkstar42** [comment]
https://www.andrewkroh.com/puppet/2015/03/08/managing-a-firewall-with-puppet-when-using-docker.html

**Comment by martialblog** [comment]
Merged new rules into refactor branch. Needs a little bit more testing and I think we can merge.

**Comment by martialblog** [comment]
Is currently excluded in production. Therefore merged
https://github.com/vision-it/vision-firewall/pull/2
